config:
  service: omnigent-server
  slack_channel: workspaces-conductor-ops

  k8s:
    name: omnigent-server
    namespace: workspaces

  targets:
    - name: staging
      selector: 'cluster.name in ["kyogre.us1.ddbuild.staging.dog"]'
