---
# consul-template renders this Vault value directly into a memory-backed volume.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-hab-vault-template
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    tags.datadoghq.com/service: {{ $.Chart.Name }}
    team: {{ $.Values.team }}
data:
  token.ctmpl: |
    {% with secret "{{ required "hab.vaultPath is required" $.Values.hab.vaultPath }}" %}{% .Data.data.{{ required "hab.vaultKey is required" $.Values.hab.vaultKey }} %}{% end %}
