apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.team }}
  labels:
    team: {{ $.Values.team }}
    app: {{ $.Chart.Name }}
    chart_name: {{ $.Chart.Name }}
    service: {{ $.Chart.Name }}
    chart_version: {{ .Chart.Version }}
    admission.datadoghq.com/mutate-pods: "true"
    admission.datadoghq.com/validate-pods: "true"
    admission.datadoghq.com/validate-services: "true"
